### ISSUE TITLE
Applying java:VirtualInvokes takes too long time

### ISSUE THREAD

**Issue by jonbe242** [jQAssistant/jqa-java-plugin#27]
I have a rather large system where analyzing using java:VirtualInvokes takes too long time for it to be a viable option.

I terminated the task after 20h on a machine using 12GB of memory for the JVM (1.8.0_202-b08, 64 bit) and an Intel i5-8250U CPU.

Running 

MATCH
  (method:Method)-[invokes:INVOKES]->(invokedMethod:Method),
  (overridingMethod:Method)-[:OVERRIDES]->(invokedMethod)
RETURN
  count(method) AS VirtualInvokes

yields about 50 000 000 VirtualInvokes, and that query took about 80 seconds.

It looks like the JVM starts to stall due to frequent GC-ing after a while. Live set + fragmentation was about 80% in JMC.
I guess that Neo4j keeps all merged new relations in memory until all 50 M has been processed and that is causing the high memory load.

Can we make the MERGE query batch the changes to the db?
Is there any change in my setup that will improve the situation (other than increase RAM)?
Will this improve thanks to #25?

Just for context; my end goal is to find all unused methods in the system.

**Comment by jonbe242** [comment]
Trying to solve this using apoc.periodic.iterate:
```
CALL apoc.periodic.iterate("MATCH (p:Type) RETURN p", 
"MATCH (p)-[:DECLARES]->(method:Method)-[invokes:INVOKES]->(invokedMethod:Method),
(overridingMethod:Method)-[:OVERRIDES]->(invokedMethod)
MERGE
(method)-[virtualInvokes:VIRTUAL_INVOKES{lineNumber:invokes.lineNumber}]->(overridingMethod)",
  {batchSize:10000})
```

But I get transaction errors:
```
ERROR Error while executing background job because of the following exception (the task will be killed): Transaction was marked as successful, but unable to commit transaction so rolled back.
org.neo4j.graphdb.TransactionFailureException: Transaction was marked as successful, but unable to commit transaction so rolled back.
at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:99)
at apoc.util.Util.lambda$inTxFuture$4(Util.java:240)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.internal.kernel.api.exceptions.TransactionFailureException: Transaction rolled back even if marked as successful
at org.neo4j.kernel.impl.api.KernelTransactionImplementation.failOnNonExplicitRollbackIfNeeded(KernelTransactionImplementation.java:647)
at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:589)
at org.neo4j.internal.kernel.api.Transaction.close(Transaction.java:178)
at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:77)
... 5 more
```

Using Neo4j 3.5.26 docker image with latest APOC (3.5.0.9).

**Comment by jonbe242** [comment]
Also getting a lot of:
```
LockClient[58] can't wait on resource RWLock[NODE(2035997), hash=306093877] since => LockClient[58] <-[:HELD_BY]- RWLock[NODE(2042253), hash=1397161198] <-[:WAITING_FOR]- LockClient[69] <-[:HELD_BY]- RWLock[NODE(2035997), hash=306093877]
```
